spring:
  config:
    activate:
      on-profile: develop

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

file:
  rootDir: D:/workspace/files
