name: CI Test Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-test:
    # main에 push하거나, Backend branch에서 pull_request를 요청했을 경우
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.base_ref, '/be/')) }}

    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
          
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    
    - name: Add executable permission to gradlew
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
