name: Deploy development server backend

on:
  push:
    branches: [ "main" ]
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "corretto"

    - name: Add executable permission to gradlew
      run: chmod +x ./backend/gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build -x test
        build-root-directory: ./backend
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./backend
        build-args: SPRING_PROFILES_ACTIVE="prod"
        tags: devjaewoo/openroadmaps-develop:latest
        
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
    - name: Deploy to AWS
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.AWS_SSH_USERNAME_DEVELOP }}
        host: ${{ secrets.AWS_SSH_HOST_DEVELOP }}
        key: ${{ secrets.AWS_SSH_KEY_DEVELOP }}
        script: |
          sudo docker compose pull
          sudo docker compose up --force-recreate --build -d
          sudo docker image prune -f
